-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#0f1417",
  base01 = "#0a0f12",
  base02 = "#171c1f",
  base03 = "#40484d",
  base04 = "#c0c7cd",
  base05 = "#dfe3e7",
  base06 = "#2c3134",
  base07 = "#353a3d",

  base08 = "#b8aee4",
  base09 = "#c9c1ea",
  base0A = "#b5c9d7",
  base0B = "#8ecff2",
  base0C = "#484364",
  base0D = "#004d67",
  base0E = "#364954",
  base0F = "#94b1c5",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#004d67',
  fg = '#c2e8ff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#9788d7',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8a9297',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#c9c1ea',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b5c9d7',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#1a6585',
})
