-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#121318",
  base01 = "#0d0e13",
  base02 = "#1a1b21",
  base03 = "#45464f",
  base04 = "#c5c6d0",
  base05 = "#e2e2e9",
  base06 = "#2f3036",
  base07 = "#38393f",

  base08 = "#d9a9d4",
  base09 = "#e1bbdd",
  base0A = "#c0c6dd",
  base0B = "#b2c5ff",
  base0C = "#5a3d59",
  base0D = "#304578",
  base0E = "#404659",
  base0F = "#9fa8cb",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#304578',
  fg = '#dae2ff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#ca86c2',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8f9099',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#e1bbdd',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#c0c6dd',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#485d92',
})
