-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#19120d",
  base01 = "#140d08",
  base02 = "#221a14",
  base03 = "#51443b",
  base04 = "#d6c3b7",
  base05 = "#f0dfd6",
  base06 = "#382f28",
  base07 = "#413731",

  base08 = "#bdc284",
  base09 = "#c6ca95",
  base0A = "#e4bfa7",
  base0B = "#ffb780",
  base0C = "#464a20",
  base0D = "#6d3a09",
  base0E = "#5b412f",
  base0F = "#d8a380",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#6d3a09',
  fg = '#ffdcc4', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#abb162',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#9f8d82',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#c6ca95',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#e4bfa7',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#895120',
})
